### ISSUE TITLE
Implement v1beta3 api

### ISSUE THREAD

**Issue by smarterclayton** [GoogleCloudPlatform/kubernetes#1519]
With #1225 merged, we can now move forward to v1beta3

- [ ] Implement pod templates #170 in (#2195, #5012) -- not blocking v1beta3
- [x] Missed spec issues
 - [x] Integrate resource limits #168 into v1beta3
- [x] Solve merging a v1beta1 PUT on an existing v1beta3 object (should new fields get cleared?)
- [x] Add namespace to path in v1beta3 (#2813)
- [x] Refactor internal API to v1beta3 objects (#1600)
- [x] Implement conversions between v1beta3 -> older (#1600)
- [x] Version field watch selectors (#2518)
- [x] Expose v1beta3 as an API endpoint (#2878)
- [x] Rename methods on client object from *Minions to *Nodes (#2788)
- [x] Determine how to map the resource path "nodes" to "minions" when talking to older APIs in the client (#2788)
- [x] Convert ContainerManifest (internal) to BoundPods (kubelet) #1662
 - Will be a breaking change for consumers and require recreating your cluster.
- [x] Map ContainerManifest (internal) to BoundPods (external API) (in #846)
 - [x] Probably need to keep ContainerManifest internal for storing as v1beta3 (#1600)
- [ ] Determine whether we want to support live migrations from v1beta1 storage to v1beta3 storage
 - [ ] etcd key identifying storage version, wrapper around API that stops accepting new requests when this value is going to change?
- [x] test object roundtripping with lost data (vs round trips that preserve data v1beta(1|2) (#1600)
- [x] resolve #294
- [ ] Doc overhaul
- [x] Fix validation of Name for ReplicationController (#3646)

Others?

**Comment by smarterclayton** [comment]
v1beta3 is now available in master by enabling `--runtime_config=api/v1beta3` on the apiserver command line (or is on by default in the test environments).  The remaining items will be covered here.

**Comment by bgrant0607** [comment]
I'm willing to punt on `s/Container/ContainerSpec/g`. None of our subobjects (Volume, VolumeSpec, ...) adhere to this convention. The status objects do/will. Maybe that's good enough.

**Comment by bgrant0607** [comment]
Re.: Solve merging a v1beta1 PUT on an existing v1beta3 object 

I'm willing to call this user error for now. I'd like to get rid of v1beta1.

Longer term, I like the idea of storing fields that are unrepresented in a particular API version in annotations.

**Comment by smarterclayton** [comment]
Fine with me.

----- Original Message -----

**Comment by bgrant0607** [comment]
I'm going to close this. v1beta3 has been implemented. Pod templates are not blocking. More specific issues have been filed for the cleanup, tracked by #5475 and #6584.

**Comment by bgrant0607** [comment]
Announced:
http://kubernetesio.blogspot.com/2015/04/introducing-kubernetes-v1beta3.html
