### ISSUE TITLE
Support Rocket

### ISSUE THREAD

**Issue by bketelsen** [GoogleCloudPlatform/kubernetes#2725]
Rocket looks to be well planned, if a bit young, and I think they have the right ideas.  Especially when it comes to leaving the kitchen sink out of containerization.

Let's add Rocket support to Kubernetes as a first class citizen.  It might greatly simplify things like networking.

**Comment by pierrebeaucamp** [comment]
Is anyone working on this? I'm very interested in rocket + kubernetes as well, in fact this was one of the reasons I started working on a [`rkt list` subcommand](https://github.com/coreos/rocket/issues/162).

**Comment by thockin** [comment]
AFAIK nobody is working seriously on this yet.

**Comment by brendandburns** [comment]
Actually, I believe the CoreOS folks are working on it.  Kelsey Hightower
tweeted something about it yesterday.  I'll try to find the tweet.

Brendan

**Comment by kelseyhightower** [comment]
@pierrebeaucamp @brendanburns Yep, we have started on the research side of things and allocating internal resources to make this happen. Over the next couple of weeks we should see a proposal from CoreOS regarding rocket integration.

**Comment by brendandburns** [comment]
Looking forward to it!

**Comment by thockin** [comment]
Awesome!  Count me in to have an opinion, er I mean provide guidance on api
and abstractions.  :)

**Comment by pierrebeaucamp** [comment]
That's good news! I'm looking forward to hear more about this soon.

**Comment by philips** [comment]
I have enumerated the initial two design considerations for doing this in a Google Doc here:

https://docs.google.com/a/coreos.com/document/d/1NVEIQPU23eRlwXBn62VR3Sl4RthEnZvJUmlnpusDFDQ/edit#

Feel free to discuss on that doc. I am personally leaning towards the initial integration being the kubelet talking systemd to launch rkt processes.

**Comment by smarterclayton** [comment]
I would prefer that approach as well.  Are you thinking transient units or creating actual units?

**Comment by philips** [comment]
@smarterclayton It will have to create actual units with a naming scheme, I think. A restarted kubelet will need to rebuild the "what is running right now" state somehow.

**Comment by smarterclayton** [comment]
We needed something like that anyway, the metadata on the units will let us recreate our state on restart.  It does mean that we would need to push that state function under the DockerInterface (or whatever it becomes now - ContainerInterface).

You *can* traverse the transient units, but for the naive host reboot case I think there's a lot of value in letting systemd own the "what is truth" and the kubelet brings it into sync with what the master thinks is truth.

----- Original Message -----

**Comment by brendandburns** [comment]
Agree, I'd like to keep as much state as I can outside of the kubelet.

--brendan

**Comment by philips** [comment]
@smarterclayton Do you know off the top of your head if systemd lets you get the `[X-Foobar]` sections out via dbus? We could serialize any state to `[X-Kubelet]`.

**Comment by smarterclayton** [comment]
It doesn't, I asked Lennart to put it on his list a while back but haven't checked recently.  He was open to adding it - agreed that it provided value.

----- Original Message -----

**Comment by pires** [comment]
Awesome! Can't wait for this, especially after https://github.com/docker/docker/pull/10776#issuecomment-74346219

**Comment by yifan-gu** [comment]
Hi folks, 

Recently I did a rocket container runtime support for the k8s.
The branch is now in the coreos's k8s fork: https://github.com/coreos/kubernetes/pull/5

Basically in the PR, it defines the container runtime interface, and provids a rocket implementation for the interface. Since I haven't fully the abstract the existing docker code into the interface yet, I added a different code path for the container runtime/rocket.

Really eager to hear your opinions on the interface!

@dchen1107 @thockin @bgrant0607 @brendanburns

**Comment by yifan-gu** [comment]
And here is an overview for that PR:

***OVERVIEW***
This PR is an initial attempt at adding support for Rocket to Kubernetes. It is largely functional but not fully complete. We are seeking feedback on the approach and for some of the outstanding issues. More details below.

***CURRENT STATE***
- The kubelet is able to launch/stop/reconcile pods via Rocket (also with specified mount volumes)
- Pods/Containers are managed by systemd: the pod and container info is stored in unit files as a JSON string, which can be fetched to do comparison and reconciliation.

***TODO***
- [ ] Health Probing:
Exec in container, via `nsenter` directly, we have code in k8s doing this, seems to only need minor changes.
Or we can use `rkt enter`.

- [ ] Restart Policy:
Since we use systemd to supervise container process, we can bake the restart policy in the unit file (which simplifies the sync pod logic). Unfortunately this solution is not generic for other container runtimes like `docker` or other future runtimes.

- [ ] Image Puller and Security Configuration:
Implement the [image puller/throttled image puller](https://github.com/GoogleCloudPlatform/kubernetes/blob/ddae4ef439c11602a1ee861dcf366dfb6cc46008/pkg/kubelet/dockertools/docker.go#L68) interface for Rocket. Also need to add command line options to allow Rocket to trust image sources.

- [ ] Port Mappings
This needs support from Rocket: https://github.com/coreos/rocket/issues/624

- [ ] Support More `docker run` Options:
Such as capability add/drop (which is approachable now).

- [ ] Inspect the Pod/Container, Get status:
Get more runtime information about the container, like the creation time, the exit code, etc. I think most of them can be done via systemd.

- [ ] Add e2e tests for the K8S/Rocket:
TBD.


***ISSUE***
The`VolumeMounts`([{Name, Readonly, MountPath}, ...]) in a kubernetes container should also appear in ACI, otherwise we cannot mount the volumes to the path in the rkt container.


***NEXT PLAN***
Add the missing features for the current rocket implementation.
Refactor on the existing docker code to make it convergent with the new container runtime.

**Comment by ibotty** [comment]
can't that be closed? isn't it implemented in upstream kubernetes?

**Comment by philips** [comment]
@ibotty I believe so, CC @yifan-gu

**Comment by bgrant0607** [comment]
Yes
