### ISSUE TITLE
Work items for node management

### ISSUE THREAD

**Issue by ddysher** [GoogleCloudPlatform/kubernetes#2959]
Now that node status is defined (#2315), we are able to proceed with the following items:

- [ ] Manage node lifecycle
- [x] Sync node status from node controller, and remove minion registry health check
- [ ] Enable watch node changes
 - [x] watch by labels (#2662)
 - [ ] watch by fields
- [ ] Instrumentation: export node resource usage, etc.
- [x] Kill pods from unhealthy node (#4241)
- [ ] Add/Remove node from kubernetes cluster dynamically (see #267 and related ones mentioned there)
- [ ] Kill pods with unmatched node label (due to node label update, etc)
- [ ] Re-provisision unhealthy node (#5676)

I'm not able to follow all k8s dev, so this is definitely not a comprehensive list :)  Also, some of these are to be discussed, not sure if we want it.

I'll start from the first two.

**Comment by davidopp** [comment]
I'd really like to close this meta-issue in favor of separate issues for each item. This entire meta-issue is labeled as 1.0, which is deceptive because not all items are for 1.0. Also I'm not sure what some of the bullets mean. Here is my understanding of the issues that correspond to @ddysher 's list, and their current status. Could someone ( perhaps @ddysher or @bgrant0607 ) please verify/clarify?

* Manage node lifecycle -- What does this mean?

* Sync node status from node controller, and remove minion registry health check -- this is #5265 and #5399?
 
* Enable watch node changes
  * watch by labels - done in #2662
  * watch by fields - what is the purpose/goal of this?

* Instrumentation: export node resource usage, etc. - done for 1.0 (see #1625)

* Kill pods from unhealthy node - fixed in #4241

* Add/Remove node from kubernetes cluster dynamically - not done; see #267 (and related ones mentioned there)

* Kill pods with unmatched node label (due to node label update, etc) - not for 1.0 AFAIK

* Re-provisision unhealthy node - @alex-mohr / @roberthbailey are interested in this but we're definitely not going to do it for all hosting providers for 1.0

**Comment by alex-mohr** [comment]
Thanks David.  Filed #5676 for re-provisioning unhealthy nodes.

**Comment by bgrant0607** [comment]
@davidopp I believe your summary is correct.

Watch by fields -- for example, to watch conditions, for nodes that are ready, not ready, not reachable, etc. Not urgent, I don't think. The broader issue is covered by #1362.

**Comment by davidopp** [comment]
Closing this issue, as it appears issues have been filed for the relevant work (I filed #5695 for "kill pods with unmatched node label" just now.) We can use the label Brian created (component/nodecontroller) to track node controller work items now and in the future, which I think is preferable to using a meta-issue.
