### ISSUE TITLE
Flip to v1beta3

### ISSUE THREAD

**Issue by bgrant0607** [GoogleCloudPlatform/kubernetes#5475]
We should start creating PRs to flip to v1beta3, so that we can start testing and merge when ready:
- [x] enable v1beta3 by default in apiserver (https://github.com/GoogleCloudPlatform/kubernetes/pull/6098, will be in 0.15)
- [x] change to v1beta3 by default in kubectl (https://github.com/GoogleCloudPlatform/kubernetes/pull/6377)
- [x] ping all getting-started-guide maintainers to rebase onto 0.15, and change their examples to use v1beta3
- [ ] Update docs and examples (https://github.com/GoogleCloudPlatform/kubernetes/issues/6584)
- [ ] delete all getting-started-guides which are not rebased onto 0.15, and remove any from gh-pages too.
- [x] kubelet to use v1beta3 on apiserver
- [x] kubelet to expose v1beta3
- [x] kubelet to use v1beta3 for local pods
- [x] kube-proxy to use v1beta3 on apiserver
- [x] replication controller controller to use v1beta3
- [x] node controller to use v1beta3
- [x] endpoint controller to use v1beta3
- [x] use v1beta3 for etcd storage (https://github.com/GoogleCloudPlatform/kubernetes/pull/6377, `--storage_version=v1beta3`)
- [x] test v1beta3 in unit and integration tests (https://github.com/GoogleCloudPlatform/kubernetes/issues/1473)
- [x] port e2e to v1beta3
- [ ] provide a v1beta1->v1beta3 storage translation tool (https://github.com/GoogleCloudPlatform/kubernetes/issues/6583)

ref. #1519
cc @smarterclayton @lavalamp

**Comment by smarterclayton** [comment]
> On Mar 13, 2015, at 8:27 PM, Brian Grant <notifications@github.com> wrote:
> 
> We should start creating PRs to flip to v1beta3, so that we can start testing and merge when ready:
> 
>  enable v1beta3 by default in apiserver
>  change to v1beta3 by default in kubectl
>  kubelet to use v1beta3 on apiserver
>  kubelet to expose v1beta3 and use v1beta3 for local pods
>  kube-proxy to use v1beta3 on apiserver
>  replication controller controller to use v1beta3
>  node controller to use v1beta3
>  endpoint controller to use v1beta3
>  use v1beta3 for etcd storage
> There's also the issue of whether to provide a v1beta1->v1beta3 storage translation tool.
> 
At a minimum, being able to test the cluster runs correctly when content is upgraded is important.  I have my doubts.

**Comment by bgrant0607** [comment]
@smarterclayton You have your doubts that it will work correctly or that it's possible to test whether it works correctly? :-)

**Comment by smarterclayton** [comment]
Yes :)

**Comment by smarterclayton** [comment]
Since all clients use latest.Version to talk to a server, most internal code can be changed centrally.

**Comment by bgrant0607** [comment]
@smarterclayton That's convenient, assuming everything works. :-)

**Comment by nikhiljindal** [comment]
Starting with the first task: "enable v1beta3 by default in apiserver"

**Comment by nikhiljindal** [comment]
Verified that e2e tests pass even when master stops exposing v1beta1 URLs.

**Comment by nikhiljindal** [comment]
I take that back. I didnt realize that my e2e tests were running on a different branch.
I re-ran them but it looks like a bunch of tests are flaky on head: https://github.com/GoogleCloudPlatform/kubernetes/issues/7548

**Comment by davidopp** [comment]
@bgrant0607 says this can be subdivided and farmed out.

**Comment by bgrant0607** [comment]
Elimination of v1beta1 and v1beta2: #8087

**Comment by davidopp** [comment]
Any other pieces you think this can be divided into? Or the remaining work is reasonable for one person (namely @nikhiljindal )?

**Comment by bgrant0607** [comment]
I'm sure this, #5799, #6584, and #8087 could each be broken up more. There are still 150 references to v1beta1 in the repo.

I don't think there's an issue for porting e2e, but @brendandburns is working on it.

**Comment by bgrant0607** [comment]
The remaining issues are #6583, #6584, and #5799. Closing this since there are more specific issues filed.
