### ISSUE TITLE
Umbrella bug: Too many lists in k8s cluster

### ISSUE THREAD

**Issue by fgrzadkowski** [GoogleCloudPlatform/kubernetes#6564]
As reported in #6514 lists can be very heavy. Currently majority of CPU usage in apiserver is caused by list handler. We should limit this significantly.

Subtasks:
- [ ] Replication controller issues too many lists #6562
- [x] Endpoints controller issues maaany lists #6518
- [x] Scheduler is not using watch to monitor nodes #6563

@wojtek-t @lavalamp @davidopp

**Comment by wojtek-t** [comment]
#6513 may also be part of this effort.

**Comment by lavalamp** [comment]
Please see: https://github.com/GoogleCloudPlatform/kubernetes/issues/4817#issuecomment-89437368

**Comment by bprashanth** [comment]
@fgrzadkowski I don't completely understand the tradeoffs involved in swapping out those lists for watches,  thoughts on how we can avoid an Umbrella bug with %s/lists/watches down the line?

**Comment by fgrzadkowski** [comment]
@bprashanth Sorry, but I don't understand your comment. I don't think there are any tradeoffs here. Semantically we will have exactly the same logic, but without reading the same objects multiple times.

**Comment by erictune** [comment]
Listing is less error-prone than watching.  We should definitely support
clients that want to list frequently.  The reported CPU saturation does not
make sense given the quantities of data involves, suggesting a pathological
bug.   That should be fixed first.

**Comment by bprashanth** [comment]
Watching involves continuously filtering every change on the server as it occurs, while listing is just filtering all objects as they currently exist (so if an object goes from rv 1->100, all 100 are sent down the watch, but only the 100th will be sent down the list). I would expect watches to add some constant strain, especially since the watch *also* does a periodic list every 5 minutes.

**Comment by fgrzadkowski** [comment]
@erictune Please see my example in this https://github.com/GoogleCloudPlatform/kubernetes/issues/6514#issuecomment-93226784

@bprashanth I agree that listing is easier for some clients, but:
a) we already have simple libraries that make using watch very easy (watch-based cache)
b) current implementation of label/field selectors is sub-optimal
c) if we control some clients (such as controllers) we should make them as light-weight (from apiserver perspective) as possible. Obviously we will have to support lists and make them faster (see #6514 and #6800) but that's a completely separate story

**Comment by fgrzadkowski** [comment]
After fixing #6518 situation improved but we still have high number (in terms of CPU usage) of lists. This happens in density test when replication controller creates new pods. I'm debugging what's the source (I don't think it's RC).

@wojtek-t 

![list_profile](https://cloud.githubusercontent.com/assets/10820726/7273964/f537bb7c-e8f8-11e4-8b4e-faea2f8b60a2.png)

**Comment by timothysc** [comment]
@rrati ^

**Comment by davidopp** [comment]
Only remaining issue is #6562 so closing this one.
